/* Navegación, privacidad, formulario y chatbot de DataLabs. */
(function(){'use strict';
const stylesheet=document.createElement('link');stylesheet.rel='stylesheet';stylesheet.href='datalabs-hero-chat-fix.css';document.head.appendChild(stylesheet);
const toggle=document.querySelector('.menu-toggle');
const menu=document.getElementById('menu');
if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu.classList.contains('open')){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.focus()}})}
const year=document.getElementById('year');if(year)year.textContent=String(new Date().getFullYear());
const banner=document.getElementById('cookie-banner');const key='datalabs-cookie-consent-v1';const saved=(()=>{try{return localStorage.getItem(key)}catch(_){return null}})();
const chatEntry=document.createElement('button');chatEntry.type='button';chatEntry.className='datalabs-chat-entry';chatEntry.setAttribute('aria-label','Abrir asistente virtual de DataLabs');chatEntry.setAttribute('title','Chat de DataLabs');chatEntry.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2C6.48 2 2 5.94 2 10.8c0 2.33 1.04 4.44 2.73 6.01L4 22l5.03-2.41c.95.27 1.94.41 2.97.41 5.52 0 10-3.94 10-8.8S17.52 2 12 2Zm-5 7h10v1.7H7V9Zm0 3.5h7v1.7H7v-1.7Z"/></svg>';document.body.appendChild(chatEntry);
let chatLoaded=false;let chatPromise=null;
async function initChat(openAfterLoad=false){if(chatLoaded){chatEntry.hidden=true;if(openAfterLoad)document.querySelector('#n8n-chat .chat-window-toggle')?.click();return}if(chatPromise){await chatPromise;if(openAfterLoad)openChatWhenReady();return}chatPromise=(async()=>{try{const module=await import('https://cdn.jsdelivr.net/npm/@n8n/chat/dist/chat.bundle.es.js');module.createChat({webhookUrl:'https://sswebhookss.affirmatechnology.com/webhook/be1293ae-db62-4ab3-8204-d2ae42505d63/chat',webhookConfig:{method:'POST',headers:{}},target:'#n8n-chat',mode:'window',chatInputKey:'chatInput',chatSessionKey:'sessionId',showWelcomeScreen:true,defaultLanguage:'es',initialMessages:['Buenas tardes 👋 Soy Fátima, asistente de DataLabs. ¿Qué proceso de datos te gustaría automatizar?'],i18n:{es:{title:'DataLabs',subtitle:'Asistente virtual',footer:'',getStarted:'INICIAR CONVERSACIÓN',inputPlaceholder:'Escribe tu mensaje...'}}});chatLoaded=true;chatEntry.hidden=true;if(openAfterLoad)openChatWhenReady()}catch(error){chatLoaded=false;chatEntry.hidden=false;console.error('No se pudo iniciar el chat:',error)}finally{chatPromise=null}})();await chatPromise}
function openChatWhenReady(attempt=0){const nativeToggle=document.querySelector('#n8n-chat .chat-window-toggle');if(nativeToggle){nativeToggle.click();return}if(attempt<25)setTimeout(()=>openChatWhenReady(attempt+1),100)}
function consent(choice){try{localStorage.setItem(key,choice)}catch(_){}if(banner)banner.hidden=true;if(choice==='accepted')initChat()}
if(banner){banner.hidden=!!saved;document.getElementById('cookie-accept')?.addEventListener('click',()=>consent('accepted'));document.getElementById('cookie-reject')?.addEventListener('click',()=>consent('rejected'));document.getElementById('cookie-close')?.addEventListener('click',()=>consent('dismissed'))}if(saved==='accepted')initChat();
chatEntry.addEventListener('click',()=>{if(saved!=='accepted'){try{localStorage.setItem(key,'accepted')}catch(_){}if(banner)banner.hidden=true}initChat(true)});
const form=document.getElementById('contact-form');const status=document.getElementById('form-status');if(form&&status){form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('[type=submit]');button.disabled=true;status.dataset.state='';status.textContent='Enviando tu consulta…';const data=new FormData(form);const payload={nombre:data.get('nombre'),empresa:data.get('empresa'),email:data.get('email'),telefono:data.get('telefono'),mensaje:data.get('mensaje')};try{const response=await fetch('/api/contacto',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Respuesta no válida del servidor');const result=await response.json();if(!result.ok)throw new Error('No se ha confirmado el envío');status.dataset.state='success';status.textContent='Tu consulta se ha enviado correctamente. Nos pondremos en contacto contigo.';form.reset()}catch(error){status.dataset.state='error';status.textContent='No hemos podido enviar la consulta. Inténtalo de nuevo o llámanos al +34 910 05 40 12.';console.error('Error al enviar formulario:',error)}finally{button.disabled=false}})}
})();
